import React from 'react';
import * as s from './SharedFileListStyled';

const SharedFileListPresenter = ({ ...props }) => {
    return (
        <s.Wrapper>
            <s.Container>
                <s.FileGroupTitle>공유받은 파일</s.FileGroupTitle>
                <s.FileDescription>
                    <s.DescriptionCheckArea>체크</s.DescriptionCheckArea>
                    <s.DescriptionTitle>제목</s.DescriptionTitle>
                    <s.DescriptionFileSize>파일 크기</s.DescriptionFileSize>
                </s.FileDescription>
                <s.FileListContainer>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>

                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>

                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>

                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                    <s.File>
                        <s.FileCheckArea>체크</s.FileCheckArea>
                        <s.FileTitle>제목</s.FileTitle>
                        <s.FileSize>파일사이즈</s.FileSize>
                    </s.File>
                </s.FileListContainer>
            </s.Container>
        </s.Wrapper>
    );
};

export default SharedFileListPresenter;